[package]
name = "bevy_embedded_assets"
version = "0.4.0-dev"
authors = ["François Mockers <mockersf@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "assets"]
readme = "README.md"
description = "A Bevy plugin to embed assets in your game"
repository = "https://github.com/vleue/bevy_embedded_assets"
categories = ["game-development"]


[dependencies]
bevy = { version = "0.8.0-dev", default-features = false, git = "https://github.com/bevyengine/bevy", features = ["bevy_asset"] }

[build-dependencies]
cargo-emit = "0.2.1"
